# Generated by Django 3.2.4 on 2021-06-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('goal', models.TextField(max_length=255)),
                ('drive_folder', models.URLField()),
                ('paying', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pm.client')),
                ('project_name', models.CharField(max_length=100)),
            ],
            bases=('pm.client',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('time_estimate', models.DurationField()),
                ('done', models.BooleanField()),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.deliverable')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('stop', models.DateTimeField(auto_now=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.deliverable')),
                ('working', models.ManyToManyField(related_name='sessions', related_query_name='session', to='pm.Step')),
            ],
        ),
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.project'),
        ),
    ]
